### ISSUE TITLE
Typo in cellosaurus.obo

### ISSUE THREAD

**Issue by vasiliy-bout** [calipho-sib/cellosaurus#1]
We tried to convert `cellosaurus.obo` to `cellosaurus.owl` using these instructions: https://github.com/owlcollab/oboformat#how-to-convert

But all the time we were getting an error:

```
java.io.IOException: org.semanticweb.owlapi.model.OWLOntologyStorageException: http://purl.obolibrary.org/obo/TEMP#%22
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:441)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414)
        at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:143)
        at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242)
        at org.obolibrary.robot.CommandManager.execute(CommandManager.java:177)
        at org.obolibrary.robot.CommandManager.main(CommandManager.java:135)
        at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48)
Caused by: org.semanticweb.owlapi.model.OWLOntologyStorageException: http://purl.obolibrary.org/obo/TEMP#%22
        at org.coode.owlapi.rdf.rdfxml.RDFXMLOntologyStorer.storeOntology(RDFXMLOntologyStorer.java:88)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182)
        at org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126)
        at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001)
        at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:438)
        ... 6 more
Caused by: org.coode.xml.IllegalElementNameException: Illegal Element Name (Element Is Not A QName): http://purl.obolibrary.org/obo/TEMP#%22
        ... 11 more
```

(This is an error for `ROBOT` tool, but `owltools` fails with the same exception.)

After that we tried to convert `.obo` file to `.ttl` (turtle format) and this conversion succeeded. So we searched for the string `http://purl.obolibrary.org/obo/TEMP#%22` in resulting `.ttl` file, and found only one occurrence in the `CVCL_6546` class.

So we looked at this class in the original `obo` file:

```
[Term]
id: CVCL_6546
name: 4-1.10
synonym: "4-1.10"" RELATED []
subset: Cancer_cell_line
subset: Female
xref: PubMed:8274294
xref: http://www.copewithcytokines.de/cope.cgi?key=4-1.10
xref: NCIt:C3802 ! Amelanotic melanoma
xref: NCBI_TaxID:9606 ! Homo sapiens
relationship: derived_from CVCL_0132 ! A-375
```

The `synonym` line contains a strange typo: it contains 3 double-quotes characters. If we change this line as:

```
synonym: "4-1.10" RELATED []
```

Then we can successfully convert original `.obo` file to `.owl`.

**Comment by AmosBairoch** [comment]
Hi Vasiliy
The problem is that 4-1.10" with the quote is a synonym of the cell line 
4-1.10, so taking away the '"' will void the synonym.
Keeping it as you found out cause a problem to the obo format.
So I think that for the next release I will use 4-1.10'' (two single 
quotes " ' " instead of a double one.
Would that pass the converter?
Best
Amos

On 24.03.2016 15:44, Vasiliy Bout wrote:

> We tried to convert |cellosaurus.obo| to |cellosaurus.owl| using these 
> instructions: https://github.com/owlcollab/oboformat#how-to-convert
> 
> But all the time we were getting an error:
> 
> |java.io.IOException: 
> org.semanticweb.owlapi.model.OWLOntologyStorageException: 
> http://purl.obolibrary.org/obo/TEMP#%22 at 
> org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:441) at 
> org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414) at 
> org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:143) 
> at 
> org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:242) 
> at 
> org.obolibrary.robot.CommandManager.execute(CommandManager.java:177) 
> at org.obolibrary.robot.CommandManager.main(CommandManager.java:135) 
> at 
> org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:48) 
> Caused by: org.semanticweb.owlapi.model.OWLOntologyStorageException: 
> http://purl.obolibrary.org/obo/TEMP#%22 at 
> org.coode.owlapi.rdf.rdfxml.RDFXMLOntologyStorer.storeOntology(RDFXMLOntologyStorer.java:88) 
> at 
> org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.store(AbstractOWLOntologyStorer.java:182) 
> at 
> org.semanticweb.owlapi.util.AbstractOWLOntologyStorer.storeOntology(AbstractOWLOntologyStorer.java:126) 
> at 
> uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.saveOntology(OWLOntologyManagerImpl.java:1001) 
> at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:438) ... 6 
> more Caused by: org.coode.xml.IllegalElementNameException: Illegal 
> Element Name (Element Is Not A QName): 
> http://purl.obolibrary.org/obo/TEMP#%22 ... 11 more |
> 
> (This is an error for |ROBOT| tool, but |owltools| fails with the same 
> exception.)
> 
> After that we tried to convert |.obo| file to |.ttl| (turtle format) 
> and this conversion succeeded. So we searched for the string 
> |http://purl.obolibrary.org/obo/TEMP#%22| in resulting |.ttl| file, 
> and found only one occurrence in the |CVCL_6546| class.
> 
> So we looked at this class in the original |obo| file:
> 
> |[Term] id: CVCL_6546 name: 4-1.10 synonym: "4-1.10"" RELATED [] 
> subset: Cancer_cell_line subset: Female xref: PubMed:8274294 xref: 
> http://www.copewithcytokines.de/cope.cgi?key=4-1.10 xref: NCIt:C3802 ! 
> Amelanotic melanoma xref: NCBI_TaxID:9606 ! Homo sapiens relationship: 
> derived_from CVCL_0132 ! A-375 |
> 
> The |synonym| line contains a strange typo: it contains 3 
> double-quotes characters. If we change this line as:
> 
> |synonym: "4-1.10" RELATED [] |
> 
> Then we can successfully convert original |.obo| file to |.owl|.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/calipho-sib/cellosaurus/issues/1Web Bug from 
> https://github.com/notifications/beacon/AIdEcoJxSkSzyG8xdajvaiF8jWYulAyfks5pwqNogaJpZM4H4COz.gif

## 

---

Professor and Director of the Dept. of Human Protein Sciences at the Faculty of Medicine of the University of Geneva
Group leader at the SIB - Swiss Institute of Bioinformatics

Preferred email: ab@sib.swiss

## Alternative email: amos.bairoch@unige.ch

**Comment by vasiliy-bout** [comment]
Hi, AmosBairoch
Your variant with two single quotes works well with converters:

```
[Term]
id: CVCL_6546
name: 4-1.10
synonym: "4-1.10''" RELATED []
...
```

This is the chunk of the resulting OWL file for this term:

``` xml
    <!-- http://purl.obolibrary.org/obo/TEMP#CVCL_6546 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/TEMP#CVCL_6546">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10</rdfs:label>
        <oboInOwl:hasRelatedSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10&apos;&apos;</oboInOwl:hasRelatedSynonym>
        ...
    </owl:Class>
```

But I also found, that you can simply escape the double-quote character using backslash, like this:

```
[Term]
id: CVCL_6546
name: 4-1.10
synonym: "4-1.10\"" RELATED []
...
```

So the corresponding OWL chunk will be:

``` xml
    <!-- http://purl.obolibrary.org/obo/TEMP#CVCL_6546 -->

    <owl:Class rdf:about="http://purl.obolibrary.org/obo/TEMP#CVCL_6546">
        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10</rdfs:label>
        <oboInOwl:hasRelatedSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10&quot;</oboInOwl:hasRelatedSynonym>
        ...
    </owl:Class>
```

**Comment by AmosBairoch** [comment]
Great
Thanks
Amos

On 13.04.2016 17:21, Vasiliy Bout wrote:

> Hi, AmosBairoch
> Your variant with two single quotes works well with converters:
> 
> |[Term] id: CVCL_6546 name: 4-1.10 synonym: "4-1.10''" RELATED [] ... |
> 
> This is the chunk of the resulting OWL file for this term:
> 
> ```
>  
> 
>  <owl:Class  rdf:about="http://purl.obolibrary.org/obo/TEMP#CVCL_6546">
>      <rdfs:label  rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10</rdfs:label>
>      <oboInOwl:hasRelatedSynonym  rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10&apos;&apos;</oboInOwl:hasRelatedSynonym>
>      ...
>  </owl:Class>
> ```
> 
> But I also found, that you can simply escape the double-quote 
> character using backslash, like this:
> 
> |[Term] id: CVCL_6546 name: 4-1.10 synonym: "4-1.10\"" RELATED [] ... |
> 
> So the corresponding OWL chunk will be:
> 
> ```
>  
> 
>  <owl:Class  rdf:about="http://purl.obolibrary.org/obo/TEMP#CVCL_6546">
>      <rdfs:label  rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10</rdfs:label>
>      <oboInOwl:hasRelatedSynonym  rdf:datatype="http://www.w3.org/2001/XMLSchema#string">4-1.10&quot;</oboInOwl:hasRelatedSynonym>
>      ...
>  </owl:Class>
> ```
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/calipho-sib/cellosaurus/issues/1#issuecomment-209506887Web 
> Bug from 
> https://github.com/notifications/beacon/AIdEcqb0ZxWL6-gKOtJ6SQFKuGy6c-Ozks5p3QoOgaJpZM4H4COz.gif

## 

---

Professor and Director of the Dept. of Human Protein Sciences at the Faculty of Medicine of the University of Geneva
Group leader at the SIB - Swiss Institute of Bioinformatics

Preferred email: ab@sib.swiss

## Alternative email: amos.bairoch@unige.ch
