### ISSUE TITLE
Add suggestions as user types input to cell line search field

### ISSUE THREAD

**Issue by khughitt** [calipho-sib/cellosaurus#4]
Hey!

I just came across this really great resource! Couple small suggestions came to mind that could improve the user experience, so I thought I would file them..

The first suggestion is to make the search field dynamic / suggest choices as the user types; this way the user can find a cell line with only a partial match..

Ideally, synonyms would also be used to help match the desired cell line.

**Comment by AmosBairoch** [comment]
Hi
The plan is not make improvement to the full text search of the Cellosaurus on ExPAsy but rather to create an advanced search option above a SPARQL engine. But this will wait until funding is obtained to: a) Create a RDF version of the Cellosaurus, b) Put in on a Virtuoso , c) Create a user friendly interface hiding the complexity of the SPARQL syntax.
